name: CI Workflow
#https://www.phillipsj.net/posts/building-windows-and-linux-containers-with-github-actions/

on:
  release:
    types:
      - published

jobs:
  build-containers:
    name: Build Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
#        os: [windows-2019, windows-2022]
        os: [windows-2019, ubuntu-latest]
        include:
          - os: windows-2019
            base: nanoserver-1809
            file: Dockerfile.windows
            tag: mrnim94/cyclops:${{ github.event.release.tag_name }}-windows-ltsc2019-amd64
          - os: ubuntu-latest
            base: alpine-3.14
            file: Dockerfile
            tag: mrnim94/cyclops:${{ github.event.release.tag_name }}
#          - os: windows-2022
#            base: nanoserver-ltsc2022
#            file: Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker Build
        run: |
          docker build -f ${{ matrix.file }} --build-arg BASE=${{ matrix.base }} -t ${{ matrix.tag }} .
      - name: Docker Push
        run: |
          docker push ${{ matrix.tag }}
#jobs:
#  sonarqube:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          # Disabling shallow clone is recommended for improving relevancy of reporting
#          fetch-depth: 0
#      - name: SonarQube Scan
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#      #####
#      - name: Build an image from Dockerfile
#        run: |
#          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
#          format: 'table'
#          severity: 'CRITICAL,HIGH'
#          scanners: 'vuln'
#          ##https://stackoverflow.com/questions/75339407/how-to-use-the-security-checks-flag-in-trivy
#      #####
#      - name: Set env
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taurus:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/taurus:${{ env.RELEASE_VERSION }}